### ISSUE TITLE
Modify the name of the program

### ISSUE THREAD

**Issue by BieberleA** [HZDR-FWDF/PARIS#26]
... do we find something in the StarTrek universe like I proposed as alternative for ddrf?

**Comment by BieberleA** [comment]
SPICA (https://en.wikipedia.org/wiki/Spica): **S**u**P**er fast 3D **I**mage re**C**onstruction  **A**ccelerator

**Comment by j-stephan** [comment]
* **Paris** - **P**ortable **A**ccelerated **R**econstruction for 3D **I**maging **S**ystems (see Lieutenant Tom Paris)

**Comment by BieberleA** [comment]
This is too common but coooool :-). What about:
PARIS - **P**ortable and **A**ccelerated 3D **R**econstruction tool for radiation based **I**maging **S**ystems

**Comment by j-stephan** [comment]
I'm okay with that.
