### ISSUE TITLE
Abandon GLADOS pipelines

### ISSUE THREAD

**Issue by j-stephan** [HZDR-FWDF/PARIS#32]
Recent profilings have shown that GLADOS pipelines no longer benefit the development of PARIS. The CUDA and OpenCL backends can easily emulate the sequential order of operations by using streams / OpenCL pipelines while the "each stage in its own thread" approach is really bad for the OpenMP backend in general.

Additionally, 50% - 90% of the runtime (depending on the backend) are spent in the backprojection kernel, forcing the other stages to wait and thus consuming more resources than necessary.

I therefore propose the removal of GLADOS pipelines from the PARIS program.

**Comment by j-stephan** [comment]
It would probably be better to use the following approach: For each available computation device, spawn a new thread (e.g. 1 Thread per GPU). Each thread does the following (in pseudocode):

```
for_each(projection_path)
{
    p = load_next_projection(); // if I/O becomes an issue, do this asynchronously

    // these are done sequentially, i.e. in the same thread of execution
    weight(p);
    filter(p);
    backproject(p);
}
save(volume);
```

**Comment by BieberleA** [comment]
Jan, where do I can find the timing profilings? Otherwise I can not follow your argumentation.

**Comment by j-stephan** [comment]
Are you attending the presentation tomorrow? Otherwise I could show you on Wednesday. I'd rather not upload them because the traces are quite large (~500MB each).

**Comment by BieberleA** [comment]
Yes, I will take part. I think a meaningful snapshot of the timing profiler is very small, isn't it? :-)

**Comment by j-stephan** [comment]
Have a look at the following histogram:

![Concurrency](https://github.com/j-stephan/fb/raw/master/presentation/thread_count.png)

You can see that there are too much threads for the given CPU (the green section is "ideal", blue is "too much"). Because every stage runs in its own thread the OpenMP runtime is used multiple times, leading to too much threads for too little cores.

Additionally, the thread management done by the pipeline introduces a lot of synchronization overhead:

![__sched_yield](https://github.com/j-stephan/fb/raw/master/presentation/call_stack.png)

Note the ``__sched_yield``. This is called internally by some of the pipeline functions when a projection is pushed to the next stage / taken from the previous stage.

**Comment by BieberleA** [comment]
Thanks ... so I will enjoy your presentation :-). By the way, is there a possibility to access your presentation via internet? GUIdo is asking.

**Comment by j-stephan** [comment]
The presentation itself is available in my GitHub repository:

https://github.com/j-stephan/fb

It is "presentation.odp", the pdf is horribly outdated.

The talk is not filmed or anything, but I believe they will try to use some videoconference software to connect with Ronny in the USA.
